// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/catalog/catalog.proto

package catalog

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CATALOG ITEM
type CatalogItem struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ItemId            string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Description       string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	QuantityAvailable uint32                 `protobuf:"varint,3,opt,name=quantity_available,json=quantityAvailable,proto3" json:"quantity_available,omitempty"`
	Price             float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CatalogItem) Reset() {
	*x = CatalogItem{}
	mi := &file_proto_catalog_catalog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CatalogItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CatalogItem) ProtoMessage() {}

func (x *CatalogItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_catalog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CatalogItem.ProtoReflect.Descriptor instead.
func (*CatalogItem) Descriptor() ([]byte, []int) {
	return file_proto_catalog_catalog_proto_rawDescGZIP(), []int{0}
}

func (x *CatalogItem) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *CatalogItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CatalogItem) GetQuantityAvailable() uint32 {
	if x != nil {
		return x.QuantityAvailable
	}
	return 0
}

func (x *CatalogItem) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

// ADD ITEM TO CATALOG
type AddCatalogItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *CatalogItem           `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCatalogItemRequest) Reset() {
	*x = AddCatalogItemRequest{}
	mi := &file_proto_catalog_catalog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCatalogItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCatalogItemRequest) ProtoMessage() {}

func (x *AddCatalogItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_catalog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCatalogItemRequest.ProtoReflect.Descriptor instead.
func (*AddCatalogItemRequest) Descriptor() ([]byte, []int) {
	return file_proto_catalog_catalog_proto_rawDescGZIP(), []int{1}
}

func (x *AddCatalogItemRequest) GetItem() *CatalogItem {
	if x != nil {
		return x.Item
	}
	return nil
}

type AddCatalogItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorMessage  string                 `protobuf:"bytes,1,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCatalogItemResponse) Reset() {
	*x = AddCatalogItemResponse{}
	mi := &file_proto_catalog_catalog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCatalogItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCatalogItemResponse) ProtoMessage() {}

func (x *AddCatalogItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_catalog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCatalogItemResponse.ProtoReflect.Descriptor instead.
func (*AddCatalogItemResponse) Descriptor() ([]byte, []int) {
	return file_proto_catalog_catalog_proto_rawDescGZIP(), []int{2}
}

func (x *AddCatalogItemResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// REMOVE ITEM FROM CATALOG
type RemoveCatalogItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveCatalogItemRequest) Reset() {
	*x = RemoveCatalogItemRequest{}
	mi := &file_proto_catalog_catalog_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveCatalogItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveCatalogItemRequest) ProtoMessage() {}

func (x *RemoveCatalogItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_catalog_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveCatalogItemRequest.ProtoReflect.Descriptor instead.
func (*RemoveCatalogItemRequest) Descriptor() ([]byte, []int) {
	return file_proto_catalog_catalog_proto_rawDescGZIP(), []int{3}
}

func (x *RemoveCatalogItemRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

type RemoveCatalogItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorMessage  string                 `protobuf:"bytes,1,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveCatalogItemResponse) Reset() {
	*x = RemoveCatalogItemResponse{}
	mi := &file_proto_catalog_catalog_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveCatalogItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveCatalogItemResponse) ProtoMessage() {}

func (x *RemoveCatalogItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_catalog_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveCatalogItemResponse.ProtoReflect.Descriptor instead.
func (*RemoveCatalogItemResponse) Descriptor() ([]byte, []int) {
	return file_proto_catalog_catalog_proto_rawDescGZIP(), []int{4}
}

func (x *RemoveCatalogItemResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// GET ITEM FROM CATALOG
type GetCatalogItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCatalogItemRequest) Reset() {
	*x = GetCatalogItemRequest{}
	mi := &file_proto_catalog_catalog_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCatalogItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCatalogItemRequest) ProtoMessage() {}

func (x *GetCatalogItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_catalog_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCatalogItemRequest.ProtoReflect.Descriptor instead.
func (*GetCatalogItemRequest) Descriptor() ([]byte, []int) {
	return file_proto_catalog_catalog_proto_rawDescGZIP(), []int{5}
}

func (x *GetCatalogItemRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

type GetCatalogItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *CatalogItem           `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCatalogItemResponse) Reset() {
	*x = GetCatalogItemResponse{}
	mi := &file_proto_catalog_catalog_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCatalogItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCatalogItemResponse) ProtoMessage() {}

func (x *GetCatalogItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_catalog_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCatalogItemResponse.ProtoReflect.Descriptor instead.
func (*GetCatalogItemResponse) Descriptor() ([]byte, []int) {
	return file_proto_catalog_catalog_proto_rawDescGZIP(), []int{6}
}

func (x *GetCatalogItemResponse) GetItem() *CatalogItem {
	if x != nil {
		return x.Item
	}
	return nil
}

func (x *GetCatalogItemResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// UPDATE ITEM QUANTITY
type UpdateQuantityAvailableRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Quantity      uint32                 `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateQuantityAvailableRequest) Reset() {
	*x = UpdateQuantityAvailableRequest{}
	mi := &file_proto_catalog_catalog_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateQuantityAvailableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateQuantityAvailableRequest) ProtoMessage() {}

func (x *UpdateQuantityAvailableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_catalog_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateQuantityAvailableRequest.ProtoReflect.Descriptor instead.
func (*UpdateQuantityAvailableRequest) Descriptor() ([]byte, []int) {
	return file_proto_catalog_catalog_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateQuantityAvailableRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *UpdateQuantityAvailableRequest) GetQuantity() uint32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type UpdateQuantityAvailableResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorMessage  string                 `protobuf:"bytes,1,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateQuantityAvailableResponse) Reset() {
	*x = UpdateQuantityAvailableResponse{}
	mi := &file_proto_catalog_catalog_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateQuantityAvailableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateQuantityAvailableResponse) ProtoMessage() {}

func (x *UpdateQuantityAvailableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_catalog_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateQuantityAvailableResponse.ProtoReflect.Descriptor instead.
func (*UpdateQuantityAvailableResponse) Descriptor() ([]byte, []int) {
	return file_proto_catalog_catalog_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateQuantityAvailableResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// UPDATE ITEM PRICE
type UpdatePriceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Price         float64                `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePriceRequest) Reset() {
	*x = UpdatePriceRequest{}
	mi := &file_proto_catalog_catalog_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePriceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePriceRequest) ProtoMessage() {}

func (x *UpdatePriceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_catalog_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePriceRequest.ProtoReflect.Descriptor instead.
func (*UpdatePriceRequest) Descriptor() ([]byte, []int) {
	return file_proto_catalog_catalog_proto_rawDescGZIP(), []int{9}
}

func (x *UpdatePriceRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *UpdatePriceRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type UpdatePriceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorMessage  string                 `protobuf:"bytes,1,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePriceResponse) Reset() {
	*x = UpdatePriceResponse{}
	mi := &file_proto_catalog_catalog_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePriceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePriceResponse) ProtoMessage() {}

func (x *UpdatePriceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_catalog_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePriceResponse.ProtoReflect.Descriptor instead.
func (*UpdatePriceResponse) Descriptor() ([]byte, []int) {
	return file_proto_catalog_catalog_proto_rawDescGZIP(), []int{10}
}

func (x *UpdatePriceResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// LISTING CATALOG
type ListCatalogItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCatalogItemsRequest) Reset() {
	*x = ListCatalogItemsRequest{}
	mi := &file_proto_catalog_catalog_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCatalogItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCatalogItemsRequest) ProtoMessage() {}

func (x *ListCatalogItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_catalog_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCatalogItemsRequest.ProtoReflect.Descriptor instead.
func (*ListCatalogItemsRequest) Descriptor() ([]byte, []int) {
	return file_proto_catalog_catalog_proto_rawDescGZIP(), []int{11}
}

type ListCatalogItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*CatalogItem         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCatalogItemsResponse) Reset() {
	*x = ListCatalogItemsResponse{}
	mi := &file_proto_catalog_catalog_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCatalogItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCatalogItemsResponse) ProtoMessage() {}

func (x *ListCatalogItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_catalog_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCatalogItemsResponse.ProtoReflect.Descriptor instead.
func (*ListCatalogItemsResponse) Descriptor() ([]byte, []int) {
	return file_proto_catalog_catalog_proto_rawDescGZIP(), []int{12}
}

func (x *ListCatalogItemsResponse) GetItems() []*CatalogItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListCatalogItemsResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_proto_catalog_catalog_proto protoreflect.FileDescriptor

const file_proto_catalog_catalog_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/catalog/catalog.proto\x12\acatalog\"\x8d\x01\n" +
	"\vCatalogItem\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12-\n" +
	"\x12quantity_available\x18\x03 \x01(\rR\x11quantityAvailable\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\"A\n" +
	"\x15AddCatalogItemRequest\x12(\n" +
	"\x04item\x18\x01 \x01(\v2\x14.catalog.CatalogItemR\x04item\"=\n" +
	"\x16AddCatalogItemResponse\x12#\n" +
	"\rerror_message\x18\x01 \x01(\tR\ferrorMessage\"3\n" +
	"\x18RemoveCatalogItemRequest\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\"@\n" +
	"\x19RemoveCatalogItemResponse\x12#\n" +
	"\rerror_message\x18\x01 \x01(\tR\ferrorMessage\"0\n" +
	"\x15GetCatalogItemRequest\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\"g\n" +
	"\x16GetCatalogItemResponse\x12(\n" +
	"\x04item\x18\x01 \x01(\v2\x14.catalog.CatalogItemR\x04item\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"U\n" +
	"\x1eUpdateQuantityAvailableRequest\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\rR\bquantity\"F\n" +
	"\x1fUpdateQuantityAvailableResponse\x12#\n" +
	"\rerror_message\x18\x01 \x01(\tR\ferrorMessage\"C\n" +
	"\x12UpdatePriceRequest\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x01R\x05price\":\n" +
	"\x13UpdatePriceResponse\x12#\n" +
	"\rerror_message\x18\x01 \x01(\tR\ferrorMessage\"\x19\n" +
	"\x17ListCatalogItemsRequest\"k\n" +
	"\x18ListCatalogItemsResponse\x12*\n" +
	"\x05items\x18\x01 \x03(\v2\x14.catalog.CatalogItemR\x05items\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage2\xa3\x04\n" +
	"\x0eCatalogService\x12Q\n" +
	"\x0eAddCatalogItem\x12\x1e.catalog.AddCatalogItemRequest\x1a\x1f.catalog.AddCatalogItemResponse\x12Z\n" +
	"\x11RemoveCatalogItem\x12!.catalog.RemoveCatalogItemRequest\x1a\".catalog.RemoveCatalogItemResponse\x12Q\n" +
	"\x0eGetCatalogItem\x12\x1e.catalog.GetCatalogItemRequest\x1a\x1f.catalog.GetCatalogItemResponse\x12l\n" +
	"\x17UpdateQuantityAvailable\x12'.catalog.UpdateQuantityAvailableRequest\x1a(.catalog.UpdateQuantityAvailableResponse\x12H\n" +
	"\vUpdatePrice\x12\x1b.catalog.UpdatePriceRequest\x1a\x1c.catalog.UpdatePriceResponse\x12W\n" +
	"\x10ListCatalogItems\x12 .catalog.ListCatalogItemsRequest\x1a!.catalog.ListCatalogItemsResponseB^Z\\github.com/MatteoBollecchino/Distributed_Programming_Project/ecommerce/proto/catalog;catalogb\x06proto3"

var (
	file_proto_catalog_catalog_proto_rawDescOnce sync.Once
	file_proto_catalog_catalog_proto_rawDescData []byte
)

func file_proto_catalog_catalog_proto_rawDescGZIP() []byte {
	file_proto_catalog_catalog_proto_rawDescOnce.Do(func() {
		file_proto_catalog_catalog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_catalog_catalog_proto_rawDesc), len(file_proto_catalog_catalog_proto_rawDesc)))
	})
	return file_proto_catalog_catalog_proto_rawDescData
}

var file_proto_catalog_catalog_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_catalog_catalog_proto_goTypes = []any{
	(*CatalogItem)(nil),                     // 0: catalog.CatalogItem
	(*AddCatalogItemRequest)(nil),           // 1: catalog.AddCatalogItemRequest
	(*AddCatalogItemResponse)(nil),          // 2: catalog.AddCatalogItemResponse
	(*RemoveCatalogItemRequest)(nil),        // 3: catalog.RemoveCatalogItemRequest
	(*RemoveCatalogItemResponse)(nil),       // 4: catalog.RemoveCatalogItemResponse
	(*GetCatalogItemRequest)(nil),           // 5: catalog.GetCatalogItemRequest
	(*GetCatalogItemResponse)(nil),          // 6: catalog.GetCatalogItemResponse
	(*UpdateQuantityAvailableRequest)(nil),  // 7: catalog.UpdateQuantityAvailableRequest
	(*UpdateQuantityAvailableResponse)(nil), // 8: catalog.UpdateQuantityAvailableResponse
	(*UpdatePriceRequest)(nil),              // 9: catalog.UpdatePriceRequest
	(*UpdatePriceResponse)(nil),             // 10: catalog.UpdatePriceResponse
	(*ListCatalogItemsRequest)(nil),         // 11: catalog.ListCatalogItemsRequest
	(*ListCatalogItemsResponse)(nil),        // 12: catalog.ListCatalogItemsResponse
}
var file_proto_catalog_catalog_proto_depIdxs = []int32{
	0,  // 0: catalog.AddCatalogItemRequest.item:type_name -> catalog.CatalogItem
	0,  // 1: catalog.GetCatalogItemResponse.item:type_name -> catalog.CatalogItem
	0,  // 2: catalog.ListCatalogItemsResponse.items:type_name -> catalog.CatalogItem
	1,  // 3: catalog.CatalogService.AddCatalogItem:input_type -> catalog.AddCatalogItemRequest
	3,  // 4: catalog.CatalogService.RemoveCatalogItem:input_type -> catalog.RemoveCatalogItemRequest
	5,  // 5: catalog.CatalogService.GetCatalogItem:input_type -> catalog.GetCatalogItemRequest
	7,  // 6: catalog.CatalogService.UpdateQuantityAvailable:input_type -> catalog.UpdateQuantityAvailableRequest
	9,  // 7: catalog.CatalogService.UpdatePrice:input_type -> catalog.UpdatePriceRequest
	11, // 8: catalog.CatalogService.ListCatalogItems:input_type -> catalog.ListCatalogItemsRequest
	2,  // 9: catalog.CatalogService.AddCatalogItem:output_type -> catalog.AddCatalogItemResponse
	4,  // 10: catalog.CatalogService.RemoveCatalogItem:output_type -> catalog.RemoveCatalogItemResponse
	6,  // 11: catalog.CatalogService.GetCatalogItem:output_type -> catalog.GetCatalogItemResponse
	8,  // 12: catalog.CatalogService.UpdateQuantityAvailable:output_type -> catalog.UpdateQuantityAvailableResponse
	10, // 13: catalog.CatalogService.UpdatePrice:output_type -> catalog.UpdatePriceResponse
	12, // 14: catalog.CatalogService.ListCatalogItems:output_type -> catalog.ListCatalogItemsResponse
	9,  // [9:15] is the sub-list for method output_type
	3,  // [3:9] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_catalog_catalog_proto_init() }
func file_proto_catalog_catalog_proto_init() {
	if File_proto_catalog_catalog_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_catalog_catalog_proto_rawDesc), len(file_proto_catalog_catalog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_catalog_catalog_proto_goTypes,
		DependencyIndexes: file_proto_catalog_catalog_proto_depIdxs,
		MessageInfos:      file_proto_catalog_catalog_proto_msgTypes,
	}.Build()
	File_proto_catalog_catalog_proto = out.File
	file_proto_catalog_catalog_proto_goTypes = nil
	file_proto_catalog_catalog_proto_depIdxs = nil
}
